import type { GlossaryTerm } from '../schema/glossary'
import { CHARAKA_SUTRA, SUSHRUTA_SUTRA } from '../sources'

export const elementTerms: GlossaryTerm[] = [
  {
    id: 'pancha-mahabhuta',
    term: 'Pancha Mahabhuta',
    devanagari: 'पञ्चमहाभूत',
    aliases: ['panchamahabhuta', 'five elements', 'five great elements', 'mahabhutas'],
    pronunciation: 'PUN-chuh muh-hah-BHOO-tuh',
    meaning:
      'The "five great elements" — space, air, fire, water, and earth. Not chemistry: these are five categories of behaviour used to describe how anything holds together or moves.',
    example:
      'A cup of tea has all five: the space in the cup, the steam moving, the heat, the liquid, and the solid leaves at the bottom.',
    relatedTerms: ['akasha', 'vayu', 'tejas', 'jala', 'prithvi', 'dosha'],
    taughtIn: ['five-elements'],
    source: CHARAKA_SUTRA('1'),
  },
  {
    id: 'akasha',
    term: 'Akasha',
    devanagari: 'आकाश',
    aliases: ['akash', 'space', 'ether'],
    pronunciation: 'ah-KAH-shuh',
    meaning: 'Space — the element of openness and room for things to happen in.',
    example:
      'The empty part of a room is what makes it usable. Ayurveda regards that emptiness as a thing in its own right, not an absence.',
    relatedTerms: ['pancha-mahabhuta', 'vata'],
    taughtIn: ['five-elements'],
    source: CHARAKA_SUTRA('1'),
  },
  {
    id: 'vayu',
    term: 'Vayu',
    devanagari: 'वायु',
    aliases: ['vaayu', 'air', 'wind'],
    pronunciation: 'VAH-yoo',
    meaning: 'Air — the element of movement, direction, and dryness.',
    example: 'Wind on a hilltop: it moves things, it dries things, and it never sits still.',
    relatedTerms: ['pancha-mahabhuta', 'vata'],
    taughtIn: ['five-elements'],
    source: CHARAKA_SUTRA('1'),
  },
  {
    id: 'tejas',
    term: 'Tejas',
    devanagari: 'तेजस्',
    aliases: ['agni element', 'fire', 'teja'],
    pronunciation: 'TAY-jus',
    meaning: 'Fire — the element of heat, light, and turning one thing into another.',
    example: 'A cooking flame does not move the pan or fill it; it changes what is inside it.',
    relatedTerms: ['pancha-mahabhuta', 'pitta', 'agni'],
    taughtIn: ['five-elements'],
    source: CHARAKA_SUTRA('1'),
  },
  {
    id: 'jala',
    term: 'Jala',
    devanagari: 'जल',
    aliases: ['ap', 'apas', 'water'],
    pronunciation: 'JUH-luh',
    meaning: 'Water — the element of cohesion, flow, and moistness.',
    example: 'Water is what makes flour into dough: it holds separate things together.',
    relatedTerms: ['pancha-mahabhuta', 'kapha', 'pitta'],
    taughtIn: ['five-elements'],
    source: SUSHRUTA_SUTRA('41'),
  },
  {
    id: 'prithvi',
    term: 'Prithvi',
    devanagari: 'पृथ्वी',
    aliases: ['prithivi', 'earth', 'pruthvi'],
    pronunciation: 'PRIT-hvee',
    meaning: 'Earth — the element of solidity, weight, and staying put.',
    example: 'A stone bench in a park. It has mass, it resists change, and it is still there next year.',
    relatedTerms: ['pancha-mahabhuta', 'kapha'],
    taughtIn: ['five-elements'],
    source: SUSHRUTA_SUTRA('41'),
  },
  {
    id: 'shad-rasa',
    term: 'Shad Rasa',
    devanagari: 'षड्रस',
    aliases: ['six tastes', 'shadrasa', 'sad rasa', 'rasas'],
    pronunciation: 'shud RUH-suh',
    meaning:
      'The six tastes — sweet, sour, salty, pungent, bitter, and astringent. Ayurveda regards taste as information about what a food will do, not merely how it is enjoyed.',
    example:
      'A squeeze of lemon (sour) on something rich changes how the whole dish sits with you. That observation is the entire idea.',
    relatedTerms: ['madhura', 'amla', 'lavana', 'katu', 'tikta', 'kashaya', 'guna'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'madhura',
    term: 'Madhura',
    aliases: ['sweet', 'madhur'],
    pronunciation: 'MUH-dhoo-ruh',
    meaning: 'The sweet taste — building and settling. Found in grains, milk, ripe fruit, root vegetables.',
    example: 'Rice and milk: the taste you reach for when you want to feel steadier, not sharper.',
    relatedTerms: ['shad-rasa', 'kapha'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'amla',
    term: 'Amla',
    aliases: ['sour'],
    pronunciation: 'UM-luh',
    meaning: 'The sour taste — warming and appetite-rousing. Found in citrus, yoghurt, fermented foods.',
    example: 'The way a pickle alongside a plain meal suddenly makes you hungrier.',
    relatedTerms: ['shad-rasa', 'pitta'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'lavana',
    term: 'Lavana',
    aliases: ['salty', 'lavan'],
    pronunciation: 'LUH-vuh-nuh',
    meaning: 'The salty taste — moistening and softening. Found in salt and sea foods.',
    example: 'Salt draws water out of a cucumber. Ayurveda reads that as the taste doing something, not just seasoning.',
    relatedTerms: ['shad-rasa', 'kapha', 'pitta'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'katu',
    term: 'Katu',
    aliases: ['pungent', 'spicy'],
    pronunciation: 'KUH-too',
    meaning: 'The pungent taste — heating and drying. Found in chilli, ginger, black pepper, mustard.',
    example: 'Chilli makes you sweat and clears a blocked nose. Heating and drying, exactly as described.',
    relatedTerms: ['shad-rasa', 'pitta', 'vata'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'tikta',
    term: 'Tikta',
    aliases: ['bitter'],
    pronunciation: 'TIK-tuh',
    meaning: 'The bitter taste — cooling and lightening. Found in leafy greens, turmeric, fenugreek.',
    example: 'A plate of bitter greens feels light in a way a plate of buttered potatoes does not.',
    relatedTerms: ['shad-rasa', 'pitta', 'kapha'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'kashaya',
    term: 'Kashaya',
    aliases: ['astringent', 'kashay'],
    pronunciation: 'kuh-SHAH-yuh',
    meaning: 'The astringent taste — drying and contracting. Found in beans, pomegranate, unripe banana, strong tea.',
    example: 'The puckering, mouth-drying feeling of over-brewed tea. That sensation is the taste category.',
    relatedTerms: ['shad-rasa', 'vata'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'virya',
    term: 'Virya',
    aliases: ['veerya', 'potency'],
    pronunciation: 'VEER-yuh',
    meaning:
      'The heating or cooling effect a food has once it is inside you, which is not always what its taste suggests.',
    example:
      'Lemon tastes sharp and sour but is classically described as warming, while mint tastes hot on the tongue and is described as cooling.',
    relatedTerms: ['shad-rasa', 'vipaka'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
  {
    id: 'vipaka',
    term: 'Vipaka',
    aliases: ['vipak', 'post-digestive effect'],
    pronunciation: 'vih-PAH-kuh',
    meaning: 'The effect a food has after digestion is finished — its longer-term influence rather than its immediate one.',
    example:
      'How a meal leaves you feeling the next morning, rather than how it tasted going down.',
    relatedTerms: ['shad-rasa', 'virya', 'agni'],
    taughtIn: ['six-tastes'],
    source: CHARAKA_SUTRA('26'),
  },
]
